language: go

go:
  #- 1.4
  #- 1.5
  - 1.6
  #- tip

install:
  - go get gopkg.in/check.v1
  - go get github.com/stretchr/testify/assert
  - go get github.com/xlab-si/e2ee-server

services:
  - postgresql  

before_script:
  - psql -c 'create database e2ee;' -U postgres
  - sudo redis-server /etc/redis/redis.conf --requirepass 'some_password'
  
script: 
  - go test -v ./tests/unit_tests
  - go test -v ./tests/api_tests
  
env:
  - ENV_TESTS_PRIV=$TRAVIS_BUILD_DIR/settings/keys/private_key
  - ENV_TESTS_PUB=$TRAVIS_BUILD_DIR/settings/keys/public_key.pub
  - ENV_TESTS_JWT=72

