language: go

#sudo: false # for container based testing

go:
  #- 1.4
  #- 1.5
  - 1.6
  #- tip
#go_import_path

install:
  - go get gopkg.in/check.v1
  - go get github.com/stretchr/testify/assert

services:
  - postgresql  

before_script:
  - psql -c 'create database e2ee;' -U postgres
  - sudo redis-server /etc/redis/redis.conf --requirepass 'some_password'
  
script: 
  - go test -v ./tests/unit_tests
  - go test -v ./tests/api_tests
  
 

