language: go

go:
  - 1.6
  - tip

go_import_path: github.com/xlab-si/e2ee-server
  
install:
  - go get gopkg.in/check.v1
  - go get github.com/stretchr/testify/assert
  - go get -u -f github.com/mancabizjak/e2ee-server

services:
  - postgresql  

before_script:
  - psql -c 'create database e2ee;' -U postgres
  
script: 
  - go test -v ./tests/api_tests

